In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(np.array(mylist))

numpy.ndarray

In [4]:
arr = np.array(mylist)

In [5]:
arr

array([1, 2, 3])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [11]:
np.linspace(0,11,10)

array([  0.        ,   1.22222222,   2.44444444,   3.66666667,
         4.88888889,   6.11111111,   7.33333333,   8.55555556,
         9.77777778,  11.        ])

In [12]:
np.linspace(0,11,100)

array([  0.        ,   0.11111111,   0.22222222,   0.33333333,
         0.44444444,   0.55555556,   0.66666667,   0.77777778,
         0.88888889,   1.        ,   1.11111111,   1.22222222,
         1.33333333,   1.44444444,   1.55555556,   1.66666667,
         1.77777778,   1.88888889,   2.        ,   2.11111111,
         2.22222222,   2.33333333,   2.44444444,   2.55555556,
         2.66666667,   2.77777778,   2.88888889,   3.        ,
         3.11111111,   3.22222222,   3.33333333,   3.44444444,
         3.55555556,   3.66666667,   3.77777778,   3.88888889,
         4.        ,   4.11111111,   4.22222222,   4.33333333,
         4.44444444,   4.55555556,   4.66666667,   4.77777778,
         4.88888889,   5.        ,   5.11111111,   5.22222222,
         5.33333333,   5.44444444,   5.55555556,   5.66666667,
         5.77777778,   5.88888889,   6.        ,   6.11111111,
         6.22222222,   6.33333333,   6.44444444,   6.55555556,
         6.66666667,   6.77777778,   6.88888889,   7.  

In [17]:
np.random.randint(0,10000,(3,3))

array([[5873, 2421, 4470],
       [5818, 1871, 5096],
       [7109, 8117, 3858]])

In [18]:
np.random.seed(101)

np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [20]:
np.random.seed(101)
arr = np.random.randint(0,100,10)

In [21]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [22]:
arr.min()

9

In [23]:
arr.max()

95

In [24]:
arr.mean()


60.799999999999997

In [25]:
arr.argmax()


0

In [26]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [27]:
mat = np.arange(0,100).reshape(10,10)

In [28]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
mat[0,1]

1

In [31]:
mat[8,9]

89

In [33]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [35]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)

In [39]:
mat[0:90].max()

99

In [44]:
import pandas as pd

In [45]:
pwd

'/home/milan/Downloads/GamePrediction/01 Introduction/002 FULL-TENSORFLOW-NOTES-AND-DATA/Tensorflow-Bootcamp-master'

In [50]:
df = pd.read_csv('salaries.csv')

In [51]:
 df

id        Name    Salary  Age
0    1       Meade    $2.38B   16
1    2       Bevan    $3.32B    2
2    3     Phillie     $1.9B   75
3    4   Aristotle  $375.34M   71
4    5       Linus  $403.79M   55
5    6     Stanley  $153.44M    6
6    7      Cosimo   $16.17B   65
7    8       Howie  $200.51M    1
8    9      Kelcie    $2.08B   68
9   10      Marney  $211.52M   14
10  11        Lena  $125.85M   81
11  12        Aggy  $599.24M   57
12  13        Zena    $1.91B   37
13  14    Martynne   $84.95M   20
14  15     Susanne   $60.28B    9
15  16       Riley   $42.28M   70
16  17     Alfredo  $637.42M   87
17  18   Micheline   $589.4M   38
18  19     Rhianon       n/a   90
19  20    Janeczka   $77.63M   40
20  21         Lib       n/a   95
21  22          Al  $832.71M    5
22  23        Jody       n/a   26
23  24      Sarita    $1.75B   90
24  25     Saundra   $79.55M   15
25  26       Valma    $1.42B   47
26  27      Cecily  $153.66M   43
27  28     Aeriela       n/a   67
28  29       Armin  $451.07M   43
29  30         Bil     $3.9B   81
30  31     Jillane    $2.29B   12
31  32       Bobby  $229.32B   69
32  33          Ev    $3.38B   48
33  34       Dyane    $1.41B   59
34  35      Mariya  $126.72M   42
35  36      Tarrah    $1.94B   28
36  37       Danny       n/a  100
37  38    Gilberte  $365.69M   29
38  39      Hunter    $2.86B   84
39  40  Bonnibelle  $613.79M   31
40  41   Christian       n/a   65
41  42       Casie   $51.15M   20
42  43       Eleni    $8.67B   43
43  44        Gage   $33.71B   49
44  45     Nananne       n/a   86
45  46       Hilly     $8.7B   50
46  47    Winthrop       n/a    5
47  48       Jaime   $82.39M   73
48  49       Vally   $48.64M   43
49  50       Royce   $10.76B   47

In [56]:
df[['Name','Salary']]

Name    Salary
0        Meade    $2.38B
1        Bevan    $3.32B
2      Phillie     $1.9B
3    Aristotle  $375.34M
4        Linus  $403.79M
5      Stanley  $153.44M
6       Cosimo   $16.17B
7        Howie  $200.51M
8       Kelcie    $2.08B
9       Marney  $211.52M
10        Lena  $125.85M
11        Aggy  $599.24M
12        Zena    $1.91B
13    Martynne   $84.95M
14     Susanne   $60.28B
15       Riley   $42.28M
16     Alfredo  $637.42M
17   Micheline   $589.4M
18     Rhianon       n/a
19    Janeczka   $77.63M
20         Lib       n/a
21          Al  $832.71M
22        Jody       n/a
23      Sarita    $1.75B
24     Saundra   $79.55M
25       Valma    $1.42B
26      Cecily  $153.66M
27     Aeriela       n/a
28       Armin  $451.07M
29         Bil     $3.9B
30     Jillane    $2.29B
31       Bobby  $229.32B
32          Ev    $3.38B
33       Dyane    $1.41B
34      Mariya  $126.72M
35      Tarrah    $1.94B
36       Danny       n/a
37    Gilberte  $365.69M
38      Hunter    $2.86B
39  Bonnibelle  $613.79M
40   Christian       n/a
41       Casie   $51.15M
42       Eleni    $8.67B
43        Gage   $33.71B
44     Nananne       n/a
45       Hilly     $8.7B
46    Winthrop       n/a
47       Jaime   $82.39M
48       Vally   $48.64M
49       Royce   $10.76B

In [57]:
df['Salary'].max()

'n/a'

In [58]:
df['Salary'].min()


'$1.41B'

In [61]:
df['Salary'].min()

'$1.41B'

In [63]:
df['Salary'].max()


'n/a'